version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v5t9f2i2
      - REPOSITORY_URI=public.ecr.aws/v5t9f2i2/go-sesa
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-40)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      #- mkdir -p ~/.docker/cli-plugins/
      #- curl --silent -L "https://github.com/docker/buildx/releases/download/v0.11.2/buildx-v0.11.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
      #- chmod a+x ~/.docker/cli-plugins/docker-buildx
      - echo "$REPOSITORY_URI:$IMAGE_TAG"
      - curl -O https://raw.githubusercontent.com/sesanetwork/sesa-genesis/main/mainnet.g
      #- docker buildx create --use
      #- docker buildx build --platform linux/arm64,linux/amd64 --tag $REPOSITORY_URI:$IMAGE_TAG -f ./docker/Dockerfile.sesa . --push
      - docker build --tag $REPOSITORY_URI:$IMAGE_TAG -f ./docker/Dockerfile.sesa . --push
  post_build:
    commands:
      - echo Build completed on `date`